### ISSUE TITLE
Add "Introduction" section to new onboarding task list

### ISSUE THREAD

**Issue by darylhedley** [hypothesis/onboarding#1]
We're creating a new task list for onboarding new engineers, see https://github.com/hypothesis/onboarding/issues/2

This issue is to add the **Introduction** section to the task list. The **Introduction** section should include:

- [x] A task for the manager to schedule a product walkthrough for the new engineer with someone from product/support
- [x] A task for the new engineer to check off when they've had the product walk through
- [x] A task for the manager to assign an onboarding buddy to the new engineer
- [x] A task for the manager to schedule a first 1:1 for the new engineer and their onboarding buddy
- [x] A task for the new engineer to check off when they've had their first 1:1 with their buddy
- [x] <del>A paragraph or two introducing the new engineer to what they're going to be doing for the rest of the onboarding process (first, second, and third months)</del> Moved to a separate issue: <https://github.com/hypothesis/onboarding/issues/33>
- [x] A task for the new engineer to (re-)read our company principles. (This time we'll actually keep track of whether they've read the document and ask them to check it off.)
- [x] <del>A task for the new engineer to get access to everything</del> This is already covered by the HR-focused onboarding check list in Notion. See [Slack thread](https://hypothes-is.slack.com/archives/CR3E3S7K8/p1659367153893379)
