### ISSUE TITLE
Add "Set up your development environment" section to new onboarding task list

### ISSUE THREAD

**Issue by darylhedley** [hypothesis/onboarding#3]
We're creating a new task list for onboarding new engineers, see https://github.com/hypothesis/onboarding/issues/2

This issue is to add the **Set up your development environment** section to the task list. The **Set up your development environment** section should include:

- [x] A task for the new engineer to read our high-level architecture documentation (note that there's a [separate issue](https://github.com/hypothesis/onboarding/issues/16) for updating our architecture documentation)
- [x] A task for the new engineer to set up their development environment and test that everything's working locally
- [x] <del>A task for the new engineer to learn how the development environment works (may require development environment documentation that doesn't exist yet)</del> Moved to a [separate issue](https://github.com/hypothesis/onboarding/issues/18) because we don't have any documentation of how the development environment works yet
- [x] A task for the engineer's buddy to arrange a call to check in and answer any questions
  - [x] A task for the engineer to check off when they've had the check in call with their buddy
