### ISSUE TITLE
Add "Make your first contribution" section to onboarding task list

### ISSUE THREAD

**Issue by darylhedley** [hypothesis/onboarding#4]
We're creating a new task list for onboarding new engineers, see https://github.com/hypothesis/onboarding/issues/2

This issue is to add the **Make your first contribution** section to the task list. The **Make your first contribution** section should include:

- [x] A task for the buddy to identify a good first issue and assign it to the new engineer
- [x] Tasks for the new engineer to (re-)read some documents that they may have already seen in their pre-onboarding email. This is the first time we'll actually keep track of whether they've read this document and ask them to check it off:
  - [x] (re-)read our Product Values
  - [x] (re-)read our Code Of Conduct
  - [x] (re-)read our Engineering Values. At this point the onboarding task list may take a paragraph to explain how the engineering values apply to making a first contribution.
- [x] A task for the new engineer to read [our guide to how to do a good PR](https://stackoverflow.com/c/hypothesis/questions/385/386)
- [x] A task for the new engineer to submit their first pull request
- [x] A task for the new engineer to find a reviewer for their first pull request
- [x] A task for the new engineer to get their first pull request approved
- [x] A task for the new engineer to read our docs on deploying pull requests (and testing changes on QA and in production)
- [x] A task for the new engineer to deploy and test their first pull request
