### ISSUE TITLE
Add "Do your first code review" section to onboarding task list

### ISSUE THREAD

**Issue by darylhedley** [hypothesis/onboarding#5]
We're creating a new task list for onboarding new engineers, see https://github.com/hypothesis/onboarding/issues/2

This issue is to add the **Do your first code review** section to the task list. The **Do your first code review** section should include:

- [ ] A task for the buddy to identify a pull request and assign it to the new engineer to review
- [ ] A task for the new engineer to re-read our Engineering Values. Yes, again. At this point the task list should take a paragraph or two to explain how the engineering values apply to doing a code review
- [ ] A task for the new engineer to read [our code review guidelines](https://stackoverflow.com/c/hypothesis/questions/303)
- [ ] A task for the new engineer to test the pull request locally (the PR description should contain testing instructions)
- [ ] A task list item for the new engineer to check off once they have approved the pull request (which may require multiple rounds of review)
