### ISSUE TITLE
Add "Do your first on-call week" section to onboarding task list

### ISSUE THREAD

**Issue by darylhedley** [hypothesis/onboarding#7]
- [ ] Why we do on-call
- [x] <del>Pagerduty</del> (this is already covered by the on-call handbook in the playbook repo)
- [x] <del>Escalation</del> (this is already covered by the on-call handbook in the playbook repo)
- [x] <del>Incident reports</del> (this is already covered by the on-call handbook in the playbook repo)
- [ ] Being on call is “done”
