### ISSUE TITLE
Add "Work on your first Project" section to onboarding task list

### ISSUE THREAD

**Issue by darylhedley** [hypothesis/onboarding#8]
The issue template should contain:

- [ ] A task for the buddy to identify a first project for the new engineer to work on. The buddy will lead this project, and the new engineer will participate.
- [ ] A task for the new engineer to read some linked-to documentation about breaking down larger tasks at the project level
- [ ] A task for the new engineer to read some linked-to documentation about cycle development
- [ ] A task for the new engineer to re-read our engineering values again (and the task list should explain why they're being asked to read these values yet again: what parts of the values apply to how we do projects)
- [ ] A task for the new engineer to read some linked-to documentation about where work comes from
- [ ] A task for the new engineer to read some linked-to documentation about initiatives & projects
- [ ] A task for the new engineer to read some linked-to documentation about tracking outcomes
- [ ] A task for the new engineer to read some linked-to documentation about what to do during downtime/being blocked
- [ ] A task for the new engineer to check off once their first project cycle has ended

**Comment by seanh** [comment]
[Does your solution solve the right problem?](https://www.intercom.com/blog/does-your-solution-solve-the-right-problem/) from the Intercom blog is an excellent post that I think we might want to get engineers to read at this stage

**Comment by seanh** [comment]
Relevant Google doc: https://docs.google.com/spreadsheets/d/1SaiBNBUjcz0RCC0oMp_ozXUeZUolpEaRucxOGmwGXm4/edit#gid=0
